version: '3.8'

services:
  ubuntu:
    container_name: my_empty_container
    image: ubuntu
    stdin_open: true
    tty: true
    command: ["/bin/bash", "-c", "apt update && apt install -y curl vim && bash"]
